### ISSUE TITLE
[It broke]: Failed to launch browser!

### ISSUE THREAD

**Issue by yuraz099** [C9Glax/tranga#356]
### What is broken?

latest image
```
services:
  tranga-api:
    platform: linux/amd64
    image: glax/tranga-api:latest
    container_name: tranga-api
    volumes:
#      - ./Manga:/Manga
#      - ./settings:/usr/share/tranga-api
      - manga:/Manga
      - settings:/usr/share/tranga-api
    ports:
      - "6531:6531"
    restart: unless-stopped
  tranga-website:
    platform: linux/amd64
    image: glax/tranga-website:latest
    container_name: tranga-website
    ports:
      - "9555:80"
    depends_on:
      - tranga-api
    restart: unless-stopped

volumes:
  manga:
  settings:
```

### Log-output

```C#
tranga-api      |  _______                                   
tranga-api      | |_     _|.----..---.-..-----..-----..---.-.
tranga-api      |   |   |  |   _||  _  ||     ||  _  ||  _  |
tranga-api      |   |___|  |__|  |___._||__|__||___  ||___._|
tranga-api      |                              |_____|       
tranga-api      | 
tranga-api      | 
tranga-api      | Unhandled exception. System.AggregateException: One or more errors occurred. (Failed to launch browser! )
tranga-api      |  ---> PuppeteerSharp.ProcessException: Failed to launch browser! 
tranga-api      |    at PuppeteerSharp.States.ProcessStartingState.StartCoreAsync(LauncherBase p) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/States/ProcessStartingState.cs:line 83
tranga-api      |    at PuppeteerSharp.States.ProcessStartingState.StartCoreAsync(LauncherBase p) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/States/ProcessStartingState.cs:line 89
tranga-api      |    at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 77
tranga-api      |    at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 110
tranga-api      |    at Tranga.MangaConnectors.ChromiumDownloadClient.StartBrowser(Logger logger) in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 18
tranga-api      |    --- End of inner exception stack trace ---
tranga-api      |    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
tranga-api      |    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
tranga-api      |    at Tranga.MangaConnectors.ChromiumDownloadClient..ctor(GlobalBase clone) in /src/Tranga/MangaConnectors/ChromiumDownloadClient.cs:line 59
tranga-api      |    at Tranga.MangaConnectors.Mangaworld..ctor(GlobalBase clone) in /src/Tranga/MangaConnectors/Mangaworld.cs:line 12
tranga-api      |    at Tranga.Tranga..ctor(Logger logger) in /src/Tranga/Tranga.cs:line 18
tranga-api      |    at Tranga.Tranga.Main(String[] args) in /src/Tranga/TrangaArgs.cs:line 49
```
