### ISSUE TITLE
Can't add Komga or Gotify..

### ISSUE THREAD

**Issue by jontstaz** [C9Glax/tranga#42]
Whenever I try to add my Komga library and Gotify and hit "Update", nothing seems to happen. I check the console log and it shows `TypeError: json.libraryManagers is undefined` (in Firefox) which I assume is the issue at least for Komga. In Chrome however I get a different error in console, `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')`. Not sure why it's happening though. And for Gotify similar issue because all the settings are still marked with the red "X" and I don't have any notifications in my Gotify for Tranga. Is this a known issue or has something just got wrong on my end? The API URI is set correctly at least as it appears in my cookies.

**Comment by C9Glax** [comment]
Ah yes that is something I forgot to change with the website.
If you check the docker-logs (`docker logs tranga-api`) there should be a notice about it still being added.
So it should be working in the background, it's just that the display is not working on the website.

If that's the case, then I won't be fixing that for the time being (in regards to #41 )

**Comment by jontstaz** [comment]
Well I'm not getting any notifications to my Gotify server, nor is it refreshing metadata automatically in Komga on new downloads, etc. So it's seemingly not actually connected to Gotify or Komga.

**Comment by C9Glax** [comment]
Okay that's not good.
Can you show the logs around the timeframe you try and add Gotify?

**Comment by Leaguesman** [comment]
I'm not the OP but I'm having the exact same issue. The logs have seemingly nothing relevant in them I'm afraid (see attachments for logs from both Docker containers from a fresh start, where I immediately attempt to connect Komga).

[tranga-api.txt](https://github.com/C9Glax/tranga/files/12328671/tranga-api.txt)
[tranga-website.txt](https://github.com/C9Glax/tranga/files/12328678/tranga-website.txt)

**Comment by mgrimace** [comment]
> Ah yes that is something I forgot to change with the website. If you check the docker-logs (`docker logs tranga-api`) there should be a notice about it still being added. So it should be working in the background, it's just that the display is not working on the website.
> 
> If that's the case, then I won't be fixing that for the time being (in regards to #41 )

same issue here, and the logs do not show anything being added:

```[08/24/2023 19:03:22.660]        Tranga | 
-------------------------------------------
 Starting Tranga-API
-------------------------------------------
[08/24/2023 19:03:22.663]        Tranga | Migrating...
[08/24/2023 19:03:22.669]        Tranga | Is Linux: True
[08/24/2023 19:03:22.669]        Tranga | Application-Folder: /usr/share/Tranga-API
[08/24/2023 19:03:22.669]        Tranga | Settings-File-Path: /usr/share/Tranga-API/settings.json
[08/24/2023 19:03:22.669]        Tranga | Download-Folder-Path: /Manga
[08/24/2023 19:03:22.669]        Tranga | Logfile-Path: /var/log/Tranga/log-24-8-2023-19-03-22.txt
[08/24/2023 19:03:22.669]        Tranga | Image-Cache-Path: /usr/share/Tranga-API/imageCache
[08/24/2023 19:03:22.669]        Tranga | Loading Taskmanager.
[08/24/2023 19:03:22.671]   TaskManager | 
-----------------------------------------------------------------
 |¯¯¯¯¯¯|°|¯¯¯¯¯¯\     /¯¯¯¯¯¯| |¯¯¯\|¯¯¯|  /¯¯¯¯¯¯\'   /¯¯¯¯¯¯| 
 |      | |   x  <|'  /   !   | |       '| |   (/¯¯¯\° /   !   | 
  ¯|__|¯  |__|\\__\\ /___/¯|_'| |___|\\__|  \\_____/' /___/¯|_'| 
-----------------------------------------------------------------
[08/24/2023 19:03:22.677]   TaskManager | Importing Data
[08/24/2023 19:03:22.679]   TaskManager | Exporting settings to /usr/share/Tranga-API/settings.json
[08/24/2023 19:03:22.687]      Mangasee | Downloading headless browser
[08/24/2023 19:03:22.799]   TaskManager | Exporting tasks to /usr/share/Tranga-API/tasks.json
[08/24/2023 19:03:22.846]   TaskManager | Starting TaskCheckerThread.
[08/24/2023 19:03:23.193]      Mangasee | Browser download progress: 0.00 %
[08/24/2023 19:03:23.193]      Mangasee | Browser download progress: 0.00 %
[08/24/2023 19:03:25.873]      Mangasee | Browser downloaded.
[08/24/2023 19:03:27.902]      Mangasee | Starting browser.
[08/24/2023 19:24:59.242]   MangaKatana | Getting Publications (title=berserk)
[08/24/2023 19:25:01.511]   MangaKatana | Saving image to /usr/share/Tranga-API/imageCache/fb145-l.jpg
[08/24/2023 19:25:03.645]   MangaKatana | Saving image to /usr/share/Tranga-API/imageCache/73583-l.jpg
[08/24/2023 19:25:05.647]   MangaKatana | Saving image to /usr/share/Tranga-API/imageCache/53c1d-l.jpg
[08/24/2023 19:25:07.508]   MangaKatana | Saving image to /usr/share/Tranga-API/imageCache/88b34-l.jpg
[08/24/2023 19:25:09.508]   MangaKatana | Saving image to /usr/share/Tranga-API/imageCache/2542b-l.jpg
[08/24/2023 19:25:11.510]   MangaKatana | Saving image to /usr/share/Tranga-API/imageCache/33dff-l.jpg
```

Installed via docker compose with /Manga folder on a mounted SMB share. Also put Tranga-API and imageCache on the share because I wasn't sure how large the cache would get:

```
version: '3'
services:
  tranga-api:
    image: glax/tranga-api:latest
    container_name: tranga-api
    volumes:
      - /mnt/media/manga/tranga:/usr/share/Tranga-API #1 when replacing ./tranga replace #2 with same value
      - /mnt/media/manga:/Manga
    ports:
      - "6531:6531"
    restart: unless-stopped
  tranga-website:
    image: glax/tranga-website:latest
    container_name: tranga-website
    volumes:
      - mnt/media/manga/tranga/imageCache:/usr/share/nginx/html/imageCache:ro #2 when replacing Point to same value as #1/imageCache
    ports:
      - "9555:80"
    depends_on: 
      - tranga-api
    restart: unless-stopped
```
