### ISSUE TITLE
[It broke]: Downloaded issues from Tranga show a "can not read" error in kavita

### ISSUE THREAD

**Issue by Paraxes** [C9Glax/tranga#91]
### What is broken?

Hello, I have a bizarre issue. I am using "Tranga" as software to download chapters and then trigger a manual scan of the library in Kavita.

However, every time Kavita shows me the "cannot read" error and tells me "There are no pages". However, if I simply copy and paste the same folder with the chapters in them on my NAS and overwrite the original files with the same files (and change nothing else, same folder and everything) and rescan via Kavita again it doesn't display any errors. 

I originally thought that Kavita was maybe picking up chapters while they are downloading, hence the error, but since I have not enabled an automatic library scan, this isn't the issue.

I also tried it with Tranga being connected to Kavita and without being connected - same error.

The chapters are acutally working if I manually open them with something like CDisplayEX for example. It almost feels like there's some kind of "flag/hidden file" (for a lack of a better term) that makes Kavita not being able to read the chapters/files initially until they are overwritten once.

Other useres in the Kavita discord have the same issues and the Kavita developer doesn't really know what the issue is, so I thought I'd ask here.

Thank you!

**Comment by C9Glax** [comment]
> I originally thought that Kavita was maybe picking up chapters while they are downloading, hence the error, but since I have not enabled an automatic library scan, this isn't the issue.

Correct, Tranga copies the completed archive.

From your description it sounds like a permission thing. Can you check if you simply change the owner of the files, if it works then?

**Comment by Paraxes** [comment]
First of all, thank you for the quick answer.

I freely admit that I am a bit of a newbie when it comes to docker. 

I deploy tranga via docker compose in portainer and just tried to add my PGID/PUID since you mentioned the permissions and do that via the usual "user" command that I know from other software however as soon as I do it Tranga sadly can't be deployed anymore.

Here's my docker compose with the user added - both the 1024:100 without quotation marks and with quotation marks "1024:100" don't make a difference in that regard. 

```
version: '3'
services:
  tranga-api:
    image: glax/tranga-api:cuttingedge
    container_name: tranga-api
    user: 1024:100
    volumes:
      - /volume1/Multimedia/zzzKavitaBib/Manga/Englisch:/Manga
      - /volume1/docker/tranga:/usr/share/tranga-api
    ports:
      - "6531:6531"
    restart: unless-stopped
  tranga-website:
    image: glax/tranga-website:cuttingedge
    container_name: tranga-website
    user: "1024:100"
    ports:
      - 9555:80
    depends_on: 
      - tranga-api
    restart: unless-stopped
```
